name: 'sigeti_dwh'
version: '1.0.0'
config-version: 2

profile: 'sigeti_dwh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sigeti_dwh:
    # Staging models - raw sources
    staging:
      +materialized: view
      +schema: staging
      
    # Dimensions - SCD Type 2 tables
    dimensions:
      +materialized: table
      +schema: dimensions
      
    # Facts - fact tables
    facts:
      +materialized: incremental
      +schema: facts
      +on_schema_change: "append_new_columns"
      
    # Data Marts - analytical views
    marts:
      +materialized: view
      +schema: marts
      compliance:
        +schema: marts_compliance
      financier:
        +schema: marts_financier
      occupation:
        +schema: marts_occupation
      clients:
        +schema: marts_clients
      operationnel:
        +schema: marts_operationnel

vars:
  # Variables for history start dates
  start_date: '2020-01-01'
  # Timezone
  timezone: 'Africa/Abidjan'
