sigeti_dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: postgres
      dbname: sigeti_node_db
      schema: dwh
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      client_encoding: utf8
      
    prod:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: postgres
      dbname: sigeti_node_db
      schema: dwh
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
      client_encoding: utf8