# Generated by Django 5.0 on 2025-12-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Serveur SMTP', max_length=100)),
                ('backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('default_from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('timeout', models.PositiveIntegerField(blank=True, help_text='Délai de connexion en secondes', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(choices=[('never', 'Jamais testé'), ('success', 'Succès'), ('failed', 'Échec')], default='never', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration SMTP',
                'verbose_name_plural': 'Configurations SMTP',
                'ordering': ['-updated_at'],
            },
        ),
    ]
