# Generated by Django 4.2.7 on 2025-11-17 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dashboard', models.CharField(choices=[('dashboard', 'Tableau de bord'), ('financier', 'Performance Financière'), ('occupation', 'Occupation Zones'), ('clients', 'Portefeuille Clients'), ('operationnel', 'KPI Opérationnels'), ('alerts', 'Alerts Analytics')], max_length=50)),
                ('scheduled_at', models.DateTimeField()),
                ('recipients', models.TextField(blank=True, help_text='Emails séparés par des virgules', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bi_report_schedules',
                'managed': True,
            },
        ),
    ]
