# Generated by Django 4.2.7 on 2025-11-17 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0002_reportschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.CharField(choices=[('dashboard', 'Tableau de bord'), ('financier', 'Performance Financière'), ('occupation', 'Occupation Zones'), ('portefeuille', 'Portefeuille Clients'), ('operationnel', 'KPI Opérationnels')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bi_user_dashboard_permissions',
                'managed': True,
                'unique_together': {('user', 'dashboard')},
            },
        ),
    ]
