# Generated by Django 5.0 on 2025-12-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_reportschedule_multiple_dashboards'),
    ]

    operations = [
        migrations.CreateModel(
            name='MartCreancesAgees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('nombre_creances', models.IntegerField(blank=True, null=True)),
                ('montant_creances', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('montant_recouvre', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('taux_recouvrement_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"dwh_marts_financier"."mart_creances_agees"',
                'ordering': ['-annee', '-mois'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MartEmploisCrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('nombre_emplois_crees', models.IntegerField(blank=True, null=True)),
                ('nombre_cdi', models.IntegerField(blank=True, null=True)),
                ('nombre_cdd', models.IntegerField(blank=True, null=True)),
                ('montant_salaires', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"dwh_marts_rh"."mart_emplois_crees"',
                'ordering': ['-annee', '-mois'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MartImplantationSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('nombre_implantations', models.IntegerField(blank=True, null=True)),
                ('nombre_etapes', models.IntegerField(blank=True, null=True)),
                ('etapes_terminees', models.IntegerField(blank=True, null=True)),
                ('etapes_en_retard', models.IntegerField(blank=True, null=True)),
                ('taux_completude_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"dwh_marts_implantation"."mart_implantation_suivi"',
                'ordering': ['-annee', '-mois'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MartIndemnisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField()),
                ('zone_name', models.CharField(blank=True, max_length=255, null=True)),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('annee_mois', models.CharField(blank=True, max_length=10, null=True)),
                ('statut', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_indemnisations', models.IntegerField(blank=True, null=True)),
                ('nombre_beneficiaires', models.IntegerField(blank=True, null=True)),
                ('montant_total_restant', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('montant_moyen', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': '"dwh_marts_financier"."mart_indemnisations"',
                'ordering': ['-annee', '-mois'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='pdfs_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionnaire stockant les chemins des PDFs générés: {dashboard_name: file_path}'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='dashboards',
            field=models.JSONField(default=list, help_text='Liste des dashboards à inclure dans le rapport'),
        ),
    ]
