version: 2

sources:
  - name: sigeti_source
    description: "SIGETI source database"
    database: "{{ env_var('SOURCE_DB_NAME', 'sigeti_node_db') }}"
    schema: public
    
    tables:
      - name: entreprises
        description: "Companies registered in the system"
        columns:
          - name: id
            description: "Unique identifier"
            tests:
              - unique
              - not_null
              
      - name: lots
        description: "Land parcels in industrial zones"
        columns:
          - name: id
            description: "Unique lot identifier"
            tests:
              - unique
              - not_null
              
      - name: zones_industrielles
        description: "Industrial zones"
        columns:
          - name: id
            tests:
              - unique
              - not_null
              
      - name: factures
        description: "Issued invoices"
        columns:
          - name: id
            tests:
              - unique
              - not_null
              
      - name: paiement_factures
        description: "Invoice payments"
        
      - name: demandes_attribution
        description: "Lot allocation requests"
        
      - name: collectes
        description: "Revenue collection operations"
        
      - name: indemnisations
        description: "Indemnifications for beneficiaries"
        
      - name: ayants_droits
        description: "Indemnification beneficiaries"
        
      - name: domaines_activites
        description: "Business sectors"
        
      - name: operateurs
        description: "System operators"
        
      - name: decisions_commission
        description: "Allocation committee decisions"
        
      - name: audit_logs
        description: "System audit logs"
        
      - name: conventions
        description: "Signed conventions"
        
      - name: purges
        description: "Purge/land release operations"
        
      - name: agents
        description: "System agents"
        
      - name: infractions
        description: "Infractions (workflow_infractions)"
        identifier: "workflow_infractions"
        
      - name: etapes_suivi_implantation
        description: "Company implementation tracking steps"
        
      - name: suivis_implantation
        description: "Main implementation tracking table"
        
      - name: demande_attribution_lots
        description: "Lots linked to attribution requests"
        
      - name: collecte_agents
        description: "Data collections by agent"
        
      - name: historique_demandes
        description: "History of actions on attribution requests - tracks all workflow transitions"
        columns:
          - name: id
            description: "Unique identifier"
          - name: demande_attribution_id
            description: "Reference to the attribution request"
          - name: utilisateur_id
            description: "User who performed the action"
          - name: action
            description: "Type of action performed"
          - name: date_action
            description: "Timestamp of the action"
          - name: etape_source
            description: "Source step number"
          - name: etape_destination
            description: "Destination step number"
            
      - name: users
        description: "System users (agents, admins)"
        columns:
          - name: id
            description: "Unique identifier"
          - name: nom
            description: "Last name"
          - name: prenoms
            description: "First names"

      - name: detenteurs
        description: "Land holders/occupants with rights"
        columns:
          - name: id
            description: "Unique identifier"
          - name: id_detenteur
            description: "External holder ID"
          - name: nom
            description: "Last name"
          - name: prenom
            description: "First name"
          - name: civilite
            description: "Title (M, Mme, Mlle)"
          - name: type_document
            description: "ID document type"
          - name: numero_piece
            description: "ID document number"

      - name: workflow_historiques
        description: "Workflow action history for impenses - tracks all actions on impense requests"
        columns:
          - name: id
            description: "Unique identifier"
          - name: impense_id
            description: "Reference to the impense"
          - name: etape
            description: "Step number V1 (1-28)"
          - name: phase
            description: "Phase number V2 (1-6)"
          - name: action
            description: "Action type (CREATION, VALIDATION, REJET, etc.)"
          - name: statut_avant
            description: "Status before action"
          - name: statut_apres
            description: "Status after action"
          - name: user_id
            description: "User who performed the action"
          - name: user_role
            description: "Role of the user at action time"
          - name: date_action
            description: "Timestamp of the action"
          - name: donnees_avant
            description: "Data before modification (JSONB)"
          - name: donnees_apres
            description: "Data after modification (JSONB)"

      - name: types_demande_impense
        description: "Types of impense requests (voluntary cession, administrative withdrawal, etc.)"
        columns:
          - name: id
            description: "Unique identifier"
          - name: code
            description: "Type code (CESSION_VOLONTAIRE, RETRAIT_ADMINISTRATIF)"
          - name: libelle
            description: "Display label"
          - name: description
            description: "Full description"
          - name: actif
            description: "Is type active"
          - name: ordre
            description: "Display order"

      - name: experts
        description: "Expert evaluators for impense assessments"
        columns:
          - name: id
            description: "Unique identifier"
          - name: nom
            description: "Expert full name"
          - name: specialite
            description: "Area of expertise"
          - name: numero_agrement
            description: "License/certification number"
          - name: date_agrement
            description: "Certification date"
          - name: organisme_agrement
            description: "Certifying organization"
          - name: actif
            description: "Is expert active"

      - name: impenses
        description: "Impense/compensation requests"
        columns:
          - name: id
            description: "Unique identifier"
          - name: numero_dossier
            description: "File number"
          - name: lot_id
            description: "Reference to the lot"
          - name: entreprise_id
            description: "Reference to the company"
          - name: statut
            description: "Current status"
