version: 2

sources:
  - name: sigeti_source
    description: "SIGETI source database"
    database: "{{ env_var('SOURCE_DB_NAME', 'sigeti_node_db') }}"
    schema: public
    
    tables:
      - name: entreprises
        description: "Companies registered in the system"
        columns:
          - name: id
            description: "Unique identifier"
            tests:
              - unique
              - not_null
              
      - name: lots
        description: "Land parcels in industrial zones"
        columns:
          - name: id
            description: "Unique lot identifier"
            tests:
              - unique
              - not_null
              
      - name: zones_industrielles
        description: "Industrial zones"
        columns:
          - name: id
            tests:
              - unique
              - not_null
              
      - name: factures
        description: "Issued invoices"
        columns:
          - name: id
            tests:
              - unique
              - not_null
              
      - name: paiement_factures
        description: "Invoice payments"
        
      - name: demandes_attribution
        description: "Lot allocation requests"
        
      - name: collectes
        description: "Revenue collection operations"
        
      - name: indemnisations
        description: "Indemnifications for beneficiaries"
        
      - name: ayants_droits
        description: "Indemnification beneficiaries"
        
      - name: domaines_activites
        description: "Business sectors"
        
      - name: operateurs
        description: "System operators"
        
      - name: decisions_commission
        description: "Allocation committee decisions"
        
      - name: audit_logs
        description: "System audit logs"
        
      - name: conventions
        description: "Signed conventions"
        
      - name: purges
        description: "Purge/land release operations"
        
      - name: agents
        description: "System agents"
        
      - name: infractions
        description: "Infractions (workflow_infractions)"
        identifier: "workflow_infractions"
        
      - name: etapes_suivi_implantation
        description: "Company implementation tracking steps"
        
      - name: suivis_implantation
        description: "Main implementation tracking table"
        
      - name: demande_attribution_lots
        description: "Lots linked to attribution requests"
        
      - name: collecte_agents
        description: "Data collections by agent"
